### ISSUE TITLE
Fallo al moverse

### ISSUE THREAD

**Issue by franciscoquintana** [N0-IDEA/Dampoly#1]
Al tirar los dados algunas veces ocurre el siguiente error:

```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at net.ddns.noidea.internal.Tablero.moverJugador(Tablero.java:132)
	at net.ddns.noidea.internal.Jugador.lanzarDados(Jugador.java:67)
	at net.ddns.noidea.Graphics.GameLayer$1.touchDown(GameLayer.java:54)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:153)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:280)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:329)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by chiptime** [comment]
Sigue roto, es necesario para cualquier trabajo con el movimiento.
